plugin:
  name: custom-data-type-geonames
  version: 1.2
  url: https://github.com/programmfabrik/easydb-custom-data-type-geonames
  displayname:
    de-DE: geonames-Verknüpfung
    en-US: geonames-Referencing
  info:
    de-DE: Stellt Verknüpfungen mit der geographischen Datenbank geonames her.
    en-US: Use for references to entities of geonames-database.
  server:
    api-version:
      require: 1
  webfrontend:
    url: custom-data-type-geonames.js
    l10n: l10n/
    css: custom-data-type-geonames.css
custom_types:
  geonames:
    mapping:
      conceptName:
        type: text
      conceptURI:
        type: text
    config:
      schema:
        - name: mapquest_api_key
          parameters:
            value:
              type: text
        - name: geonames_username
          parameters:
            value:
              type: text
      mask:
        - name: show_infopopup
          parameters:
            value:
              type: bool
        - name: config_featureclasses
          parameters:
            value:
              type: bool
